
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.11.0-25-generic - x86_64
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CheckCSourceCompiles.cmake:52 (cmake_check_source_compiles)"
      - "/usr/share/cmake-3.28/Modules/FindThreads.cmake:97 (CHECK_C_SOURCE_COMPILES)"
      - "/usr/share/cmake-3.28/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "build_wasm/_deps/googletest-src/googletest/cmake/internal_utils.cmake:65 (find_package)"
      - "build_wasm/_deps/googletest-src/googletest/CMakeLists.txt:88 (config_compiler_and_linker)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "/home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D"
      binary: "/home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/home/dan/code/emsdk/upstream/emscripten/emscan-deps"
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/home/dan/code/emsdk/upstream/emscripten/cmake/Modules;/home/dan/code/emsdk/upstream/emscripten/cmake/Modules;/home/dan/code/emsdk/upstream/emscripten/cmake/Modules;/home/dan/code/emsdk/upstream/emscripten/cmake/Modules;/home/dan/code/emsdk/upstream/emscripten/cmake/Modules"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: '/home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_b06ff/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_b06ff.dir/build.make CMakeFiles/cmTC_b06ff.dir/build
        gmake[1]: Entering directory '/home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D'
        Building C object CMakeFiles/cmTC_b06ff.dir/src.c.o
        /home/dan/code/emsdk/upstream/emscripten/emcc -DCMAKE_HAVE_LIBC_PTHREAD   -MD -MT CMakeFiles/cmTC_b06ff.dir/src.c.o -MF CMakeFiles/cmTC_b06ff.dir/src.c.o.d -o CMakeFiles/cmTC_b06ff.dir/src.c.o -c /home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D/src.c
        Linking C executable cmTC_b06ff.js
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b06ff.dir/link.txt --verbose=1
        /home/dan/code/emsdk/upstream/emscripten/emcc @CMakeFiles/cmTC_b06ff.dir/objects1.rsp -o cmTC_b06ff.js 
        gmake[1]: Leaving directory '/home/dan/code/st/build_wasm/CMakeFiles/CMakeScratch/TryCompile-eBnm8D'
        
      exitCode: 0
...
